
package web;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CreditCardSoapService", targetNamespace = "http://web/", wsdlLocation = "http://localhost:1234/ankitha?wsdl")
public class CreditCardSoapService
    extends Service
{

    private final static URL CREDITCARDSOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException CREDITCARDSOAPSERVICE_EXCEPTION;
    private final static QName CREDITCARDSOAPSERVICE_QNAME = new QName("http://web/", "CreditCardSoapService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1234/ankitha?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CREDITCARDSOAPSERVICE_WSDL_LOCATION = url;
        CREDITCARDSOAPSERVICE_EXCEPTION = e;
    }

    public CreditCardSoapService() {
        super(__getWsdlLocation(), CREDITCARDSOAPSERVICE_QNAME);
    }

    public CreditCardSoapService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CREDITCARDSOAPSERVICE_QNAME, features);
    }

    public CreditCardSoapService(URL wsdlLocation) {
        super(wsdlLocation, CREDITCARDSOAPSERVICE_QNAME);
    }

    public CreditCardSoapService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CREDITCARDSOAPSERVICE_QNAME, features);
    }

    public CreditCardSoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreditCardSoapService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CreditCardSoap
     */
    @WebEndpoint(name = "CreditCardSoapPort")
    public CreditCardSoap getCreditCardSoapPort() {
        return super.getPort(new QName("http://web/", "CreditCardSoapPort"), CreditCardSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CreditCardSoap
     */
    @WebEndpoint(name = "CreditCardSoapPort")
    public CreditCardSoap getCreditCardSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://web/", "CreditCardSoapPort"), CreditCardSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CREDITCARDSOAPSERVICE_EXCEPTION!= null) {
            throw CREDITCARDSOAPSERVICE_EXCEPTION;
        }
        return CREDITCARDSOAPSERVICE_WSDL_LOCATION;
    }

}
