
package web;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CreditCardSoap", targetNamespace = "http://web/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CreditCardSoap {


    /**
     * 
     * @return
     *     returns web.GroupOfCards
     */
    @WebMethod
    @WebResult(name = "GroupOfCards", partName = "GroupOfCards")
    @Action(input = "http://web/CreditCardSoap/readAllRequest", output = "http://web/CreditCardSoap/readAllResponse")
    public GroupOfCards readAll();

    /**
     * 
     * @param integer
     * @return
     *     returns web.GroupOfCards
     */
    @WebMethod
    @WebResult(name = "GroupOfCards", partName = "GroupOfCards")
    @Action(input = "http://web/CreditCardSoap/readAllByLimitRequest", output = "http://web/CreditCardSoap/readAllByLimitResponse")
    public GroupOfCards readAllByLimit(
        @WebParam(name = "Integer", partName = "Integer")
        int integer);

    /**
     * 
     * @param creditCard
     */
    @WebMethod
    @Action(input = "http://web/CreditCardSoap/createCardRequest", output = "http://web/CreditCardSoap/createCardResponse")
    public void createCard(
        @WebParam(name = "CreditCard", partName = "CreditCard")
        CreditCard creditCard);

    /**
     * 
     * @param creditCard
     */
    @WebMethod
    @Action(input = "http://web/CreditCardSoap/blockCardRequest", output = "http://web/CreditCardSoap/blockCardResponse")
    public void blockCard(
        @WebParam(name = "CreditCard", partName = "CreditCard")
        CreditCard creditCard);

    /**
     * 
     * @param _long
     * @return
     *     returns web.CreditCard
     */
    @WebMethod
    @WebResult(name = "CreditCard", partName = "CreditCard")
    @Action(input = "http://web/CreditCardSoap/readOneRequest", output = "http://web/CreditCardSoap/readOneResponse")
    public CreditCard readOne(
        @WebParam(name = "Long", partName = "Long")
        long _long);

}
