//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.27 at 10:07:48 AM IST 
//


package services.loans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="minTenure" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="maxTenure" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "minTenure",
    "maxTenure"
})
@XmlRootElement(name = "filterByTenureRequest")
public class FilterByTenureRequest {

    protected int minTenure;
    protected int maxTenure;

    /**
     * Gets the value of the minTenure property.
     * 
     */
    public int getMinTenure() {
        return minTenure;
    }

    /**
     * Sets the value of the minTenure property.
     * 
     */
    public void setMinTenure(int value) {
        this.minTenure = value;
    }

    /**
     * Gets the value of the maxTenure property.
     * 
     */
    public int getMaxTenure() {
        return maxTenure;
    }

    /**
     * Sets the value of the maxTenure property.
     * 
     */
    public void setMaxTenure(int value) {
        this.maxTenure = value;
    }

}
