//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.03.27 at 10:07:48 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://loans.services", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package services.loans;
