
package initial;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MySource", targetNamespace = "http://initial/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface MySource {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://initial/MySource/addDeafulterRequest", output = "http://initial/MySource/addDeafulterResponse")
    public String addDeafulter(
        @WebParam(name = "arg0", partName = "arg0")
        String arg0);

}
